title: William Pritchard
logo: headshot_circle.png
description: william.pritchard35@outlook.com
description: Analytics professional with 7 years of experience in state administrative data analysis. Excels in optimizing operations, ensuring quality, and promoting team growth. Seeking to leverage expertise in business administration and data analysis.
show_downloads: false
theme: jekyll-theme-minimal
