title: William Pritchard
logo: headshot_circle.png
description: If you are looking for a quick and fun introduction to GitHub, you've found it. This class will get you started using GitHub in less than an hour.
show_downloads: false
theme: jekyll-theme-minimal
